// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-rmnhSMhKuEezDj01S7bHVB9gZ44jK_I',
    appId: '1:904462045883:web:fbc1f37cc196fb064fcf9e',
    messagingSenderId: '904462045883',
    projectId: 'daily-2a5a6',
    authDomain: 'daily-2a5a6.firebaseapp.com',
    databaseURL: 'https://daily-2a5a6-default-rtdb.firebaseio.com',
    storageBucket: 'daily-2a5a6.appspot.com',
    measurementId: 'G-6HD4CRWJ0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB695IiEKAKDlpxz-FHExBbyagoqRGJnjg',
    appId: '1:904462045883:android:4942cfbf63362ade4fcf9e',
    messagingSenderId: '904462045883',
    projectId: 'daily-2a5a6',
    databaseURL: 'https://daily-2a5a6-default-rtdb.firebaseio.com',
    storageBucket: 'daily-2a5a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUlTS2UT-WdQVAbNA2kx8mRWBgQBI9isI',
    appId: '1:904462045883:ios:a6b95b7eb88823794fcf9e',
    messagingSenderId: '904462045883',
    projectId: 'daily-2a5a6',
    databaseURL: 'https://daily-2a5a6-default-rtdb.firebaseio.com',
    storageBucket: 'daily-2a5a6.appspot.com',
    iosClientId: '904462045883-svs7lp0h1v10k7e7udrbob9s09e22hso.apps.googleusercontent.com',
    iosBundleId: 'com.phoenix.daily',
  );
}
